### ISSUE TITLE
Please rename your project

### ISSUE THREAD

**Issue by michaelklishin** [jakubkulhan/bunny#1]
I have to be that guy but there has been a RabbitMQ client [named Bunny](http://rubybunny.info) since March 2009. Please rename your project as it will mess up search results both the users of the existing client and your own future users.

**Comment by jakubkulhan** [comment]
I don't mean to canibalize on your project's name, "bunny" was just so fitting name when starting. I've upadated README and always refer to this library as BunnyPHP, is it ok with you?

**Comment by michaelklishin** [comment]
Yes, BunnyPHP works. Thank you!
