### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by mmoreram** [jakubkulhan/bunny#104]
Would be amazing if there is a new version for this package. That would allow start using PHP^8.

Thanks!

**Comment by WyriHaximus** [comment]
@mmoreram Indeed it would be, currently I want to do a few things before tagging 0.5 as the master branch already support PHP 8. So most likely somewhere before the end of next week as I'm currently having to do some unplanned high priority work on some packages.

**Comment by WyriHaximus** [comment]
Had a go at some of the things I wanted to do before release it, but got stuck on moving to GitHub Actions and realised that adding return type hints to (at least) all public method is more work than anticipated so moved both to v0.6.0. 

So without any more delay here is [`v0.5.0`](https://github.com/jakubkulhan/bunny/releases/tag/v0.5.0)

**Comment by mmoreram** [comment]
Thanks
