### ISSUE TITLE
`react/promise` is pinned to 2.2.x

### ISSUE THREAD

**Issue by someniatko** [jakubkulhan/bunny#113]
`react/promise` is pinned to `~2.2` in the `composer.json`, effectively only allowing installation of 2.2.x versions. Is there any reason prohibiting installing newer versions of the lib?

**Comment by WyriHaximus** [comment]
Looking at the composer documentation, the detail is in the patch version: https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators

**Comment by someniatko** [comment]
Sorry, you're right, in this case `^2.2` and `~2.2` are indeed equivalent.
