### ISSUE TITLE
Compatibility with Azure Event Hubs

### ISSUE THREAD

**Issue by jbelien** [jakubkulhan/bunny#119]
Hello,

This library looks awesome and I'm trying to use it to connect to [Azure Event Hubs](https://azure.microsoft.com/en-us/services/event-hubs/) (AMQP compatible).

I'm using [`worker-async.php`](https://github.com/jakubkulhan/bunny/blob/e03224f076a21fa386b1da1b29381c3e0acab603/examples/worker-async.php) and the following connection (according to what I've found in Azure Event Hubs documentation).

```php
$clientConfig = [
    "host" => "###.servicebus.windows.net",
    "port" => 5672, // I also tried 5671
    "user" => '$ConnectionString',
    "password" => "Endpoint=sb://###.servicebus.windows.net/;SharedAccessKeyName=###;SharedAccessKey=###",
];

```

I get the following exception:

```
Uncaught Bunny\Exception\ClientException: Broken pipe or closed connection.
```

Is Bunny library compatible with Azure Event Hubs and if so how can I connect to it ?

Thanks a lot for any help or insight!

**Comment by WyriHaximus** [comment]
Hey @jbelien, which version of AMQP does event hubs support? Bunny implements AMQP 0.9.1

**Comment by jbelien** [comment]
Aaah, that's probably why : Azure Event Hubs implementins AMQP 1.0 (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide).

Thanks @WyriHaximus for the quick answer.
I'll continue my investigation. 😄
