### ISSUE TITLE
Async without ReactPHP?

### ISSUE THREAD

**Issue by SerafimArts** [jakubkulhan/bunny#133]
Hello! Thank you very much for the work done!

Can you please tell me if it is planned to add native PHP support? Would like to see something like:

```php
// Client

public function receive(): Message
{
     do {
        \Fiber::getCurrent() && \Fiber::suspend();
        $message = $this->pollMessage(); // Message|null
     } while ($message !== null);

    return $message;
}
```

```php
// Sync
$message = $channel->receive();

// Async
$first = new \Fiber($channel1->receive(...));
$second = new \Fiber($channel2->receive(...));

// ... process fibers (using "while(!$fiber->isTerminated())" + "$fiber->resume()")

$first->getReturn();
$second->getReturn();
```

**Comment by WyriHaximus** [comment]
Hey @SerafimArts, the current plan is combined both clients into one still with ReactPHP as backend and exposing a fiber based API that doesn't expose any promises.

**Comment by SerafimArts** [comment]
ReactPHP does not provide the ability to manually control the event loop. 

Like:
```php
while ($loop->isRunning()) {
    $loop->tick();

    // Do something else not related to the loop
}
```

In any case, thanks for the reply! I will think about how to solve the problem =(

**Comment by WyriHaximus** [comment]
Well what is the problem that you are trying to solve by controlling the event loop?

**Comment by SerafimArts** [comment]
The absence of a global breakpoint (i.e. the physical absence of a `while(true)`).

Well, the physical absence of the event loop, too, because. in fact, it is simply not needed =)))

**Comment by WyriHaximus** [comment]
While we officially don't recommend it, you can do something like this to control the event loop:

```php
while(true) {
    Loop::addTimer(0.01, static function (): void {Loop::stop()});
    Loop::run();
}

**Comment by SerafimArts** [comment]
It's too strong looks like a perversion)))

**Comment by WyriHaximus** [comment]
It is :joy:
