### ISSUE TITLE
PromiseInterface has not done object

### ISSUE THREAD

**Issue by AbrahamCovelo** [jakubkulhan/bunny#141]
Taking a look a this line done  method does not exist for a React\Promise\PromiseInterface

https://github.com/jakubkulhan/bunny/blob/10e34dec73397d30cb79f61dd81e9716644ede01/src/Bunny/Async/Client.php#L335

It has produces some errors in my project 

In Client.php line 340:
                                                                                        
  Attempted to call an undefined method named "done" of class "React\Promise\Promise".

**Comment by WyriHaximus** [comment]
This package doesn't target promise v3 yet:

https://github.com/jakubkulhan/bunny/blob/10e34dec73397d30cb79f61dd81e9716644ede01/composer.json#L30

So how are you getting that error?

P.S. Don't get me wrong, happy to see more and more people using Promise v3 but that shouldn't happen when you use this package yet.

**Comment by WyriHaximus** [comment]
Closing this as #147 landed promise v3 for the upcoming 0.6 release
