### ISSUE TITLE
get() should return a Message instance or NULL

### ISSUE THREAD

**Issue by Andrewsville** [jakubkulhan/bunny#15]
Right now ```get()``` returns a ```MethodBasicGetOkFrame``` instance (or ```MethodBasicGetEmptyFrame``` instance after #14). From the developers perspective that is way too lowlevel. When I call ```get()```, I expect to get a ```Message``` instance (or ```NULL``` when there is no message in the queue). Just like when I register a consumer, I expect the callback to get a ```Message``` instance and not a Frame instance.

Moreover the Frame returned by ```get()``` does not contain the payload which is probably caused by [this](https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/Protocol/ProtocolReader.php#L145).

Being very new to Bunny I have no idea why the payload is not being set. And even if it was, I still don't know how to process it to get the message contents. I can provide a PR but I need some advice :)

**Comment by jakubkulhan** [comment]
`get()` isn't implemented property at the moment, I'll look into that. Thank you for reporting this. However for real use I suggest `consume()` with message handler as it's more performant.

**Comment by jakubkulhan** [comment]
The `get()` is now implemented properly and returns `Message` in both sync and async clients. Hope this helps.
