### ISSUE TITLE
Version 1.0 - PHP7-only

### ISSUE THREAD

**Issue by jakubkulhan** [jakubkulhan/bunny#19]
- return types
- scalar type hints
- split generated methods for sync/async client

**Comment by pepakriz** [comment]
:+1:

**Comment by ondrejmirtes** [comment]
No problem for @slevomat. We already run on PHP 7. It's a pity that ReactPHP does not have any plans to move to PHP 7 and seems mostly unmantained.

**Comment by Ocramius** [comment]
:+1: here. No point in all this userland async without 7's performance
