### ISSUE TITLE
Images from rabbitmq.com

### ISSUE THREAD

**Issue by michaelklishin** [jakubkulhan/bunny#2]
I'm not sure you are aware of this but the images you've taken from rabbitmq.com are not open source (at least yet) and the footer of the site says

```
Copyright © 2015 Pivotal Software, Inc. All rights reserved
```

So unless until the RabbitMQ team gets a permission from legal to open source the site, it may be a good idea to replace them with your own images. We certainly don't want to cause anybody any trouble but you haven't even asked if it's OK to use them for your project.

**Comment by jakubkulhan** [comment]
I've withdrawn images, code samples and tutorial text. I'll contact Pivotal for permission.
