### ISSUE TITLE
Invalid Exception when payload empty

### ISSUE THREAD

**Issue by klatys** [jakubkulhan/bunny#21]
Putting aside why message payload is empty, this occured and though I'm not precisely sure whether it's even bunny's mistake here goes:
If a message with empty payload arrives it's treated as MethodBasicDeliverFrame. e.g.
```
object(Bunny\Protocol\MethodBasicDeliverFrame)#555 (11) {
  ["consumerTag"]=>
  string(31) "amq.ctag-0wiQ0mvNiMhKkINcA079XQ"
  ["deliveryTag"]=>
  int(2)
  ["redelivered"]=>
  bool(false)
  ["exchange"]=>
  string(6) "action"
  ["routingKey"]=>
  string(12) "action.#####"
  ["classId"]=>
  int(60)
  ["methodId"]=>
  int(60)
  ["type"]=>
  int(1)
  ["channel"]=>
  int(1)
  ["payloadSize"]=>
  int(65)
  ["payload"]=>
  NULL
}
```
Since after receiving Header frame, channel is in awaiting body state, the frame is treated as unexpected and exception is thrown at https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/Channel.php#L573

Any ideas why this might occur and how this should be resolved?

Env:
- Debian 8.3 Jessie
- PHP 5.6.17
- RabbitMQ 3.3.5

**Comment by jakubkulhan** [comment]
Empty messages were not handled properly. Fixed.
