### ISSUE TITLE
Mandatory not indicated

### ISSUE THREAD

**Issue by cboden** [jakubkulhan/bunny#25]
I'm setting the mandatory flag with a message that is not getting routed but not receiving an indication of the message was delivered to a queue. Here is an example where the message certainly fails to be delivered (result was the same with async client):

```php
<?php
    $c = (new \Bunny\Client)->connect();
    $ch = $c->channel();
    $result = $ch->publish('An un-routed message', [], 'amq.topic', 'nopeKey', true);

    var_dump($result);
```
> bool(true);

<img width="657" alt="screen shot 2016-05-04 at 10 33 56 am" src="https://cloud.githubusercontent.com/assets/617694/15017474/bec7d3e6-11e3-11e6-9a6a-370e805138cc.png">

**Comment by jakubkulhan** [comment]
`basic.publish` is fire-and-forget = it returns `true` right after the buffer has been flushed to network, no response is being received from the broker. 

[RabbitMQ sends `basic.return`](https://www.rabbitmq.com/confirms.html#when) when mandatory-flagged message cannot be routed to any queue. If you want to handle `basic.return`s, you can add callback to given channel:

```php

$c = new Client();
$c->connect();
$ch = $c->channel();

$ch->addReturnListener(function (Message $message, MethodBasicReturnFrame $returnFrame) {
	// handle un-routed message
});

$ch->publish('An un-routed message', [], 'amq.topic', 'nopeKey', true);
$c->run();
```
