### ISSUE TITLE
[question] How to handle reconnecting on RabbitMQ server restart

### ISSUE THREAD

**Issue by mmelvin0** [jakubkulhan/bunny#26]
I have a consumer and I'm wondering how best to recover when RabbitMQ goes away.

Currently I get a `Bunny\Exception\ClientException` thrown which kills my React event loop:

```
Fatal error: Uncaught Bunny\Exception\ClientException: Broken pipe or closed connection. in .../vendor/bunny/bunny/src/Bunny/AbstractClient.php on line 280

Bunny\Exception\ClientException: Broken pipe or closed connection. in .../vendor/bunny/bunny/src/Bunny/AbstractClient.php on line 280

Call Stack:
    0.0001     354160   1. ...
    0.0015     587600   2. ...
    0.0090    2108960   3. React\EventLoop\StreamSelectLoop->run() ...
   41.4237    2972512   4. React\EventLoop\StreamSelectLoop->waitForStreamActivity() .../vendor/react/event-loop/src/StreamSelectLoop.php:201
   41.4698    2972992   5. call_user_func:{.../vendor/react/event-loop/src/StreamSelectLoop.php:232}() .../vendor/react/event-loop/src/StreamSelectLoop.php:232
   41.4698    2972992   6. Bunny\Async\Client->onDataAvailable() .../vendor/react/event-loop/src/StreamSelectLoop.php:232
   41.4698    2972992   7. Bunny\AbstractClient->read() .../vendor/bunny/bunny/src/Bunny/Async/Client.php:292
```
I can handle the `ClientException` at the top-level of my application with:

```
while (1) {
    try {
        $loop-run();
    } catch (ClientException $ex) {
        // reconnect logic goes here
    }
}
```

That seems a little heavy-handed to me. Is this the right thing to do or is there a better way?

**Comment by ondrejmirtes** [comment]
I think there's not any reason to restart RabbitMQ broker regularly and so it's not something you should explicitly handle in your consumer. Letting the whole process restart is just fine in my opinion.

**Comment by mmelvin0** [comment]
In my environment RabbitMQ restarts will happen. My use case is a job queue with some potentially long-running jobs. If the broker is restarted I don't want to kill currently running jobs.

It should be possible to re-establish the connection and when the "start job" message is redelivered to the job executor, to immediately send or enqueue an ack for that job.

Do you think it's a better solution to kill all pending jobs if the message broker goes away?

**Comment by ondrejmirtes** [comment]
Well if the broker is restarted and the connection interrupted, you should quit processing the jobs because you have no way to ack the messages and so RabbitMQ will redeliver them again. I also recommend you to make the messages "smaller" so each message is processed faster and there is more of them. So "long running" jobs wouldn't be as long.

But the main issue here is that the restarts should not happen on regular basis.

**Comment by mmelvin0** [comment]
OK, thank you!
