### ISSUE TITLE
Mixture of properties and headers

### ISSUE THREAD

**Issue by cboden** [jakubkulhan/bunny#27]
Note: I have omitted some output fields for the sake of readability. 

It seems that when Bunny consumes messages with custom headers that were not published by Bunny the `properties` and `headers` fields are flattened. 

Given the screenshot:
<img width="743" alt="screen shot 2016-05-26 at 3 41 37 pm" src="https://cloud.githubusercontent.com/assets/617694/15587691/5d0c2f90-2358-11e6-970d-e49edb9a0810.png">
Bunny's output is:

```
Bunny\Message Object
(
    [routingKey] => props
    [headers] => Array
        (
            [user_id] => 96ce7157f70de72e08b0a8c78300bf1e
            [delivery-mode] => 1
            [user-id] => admin
        )

    [content] => Wat?
)
```

But if Bunny publishes the same message like so:

``` php
$ch->publish('Hello World!', [
    'user-id' => 'admin',
    'headers' => [
      'user_id' => '96ce7157f70de72e08b0a8c78300bf1e'
    ]
  ], '', 'props');
```

The output is as expected:

```
Bunny\Message Object
(
    [routingKey] => props
    [headers] => Array
        (
            [headers] => Array
                (
                    [user_id] => 96ce7157f70de72e08b0a8c78300bf1e
                )

            [user-id] => admin
        )
    [content] => Hello World!
)
```

---

Here is the output from a Node AMQP lib which looks the same when consuming messages published by Bunny, node.amqp, and RabbitMQ web admin:

```
 { fields: 
   { routingKey: 'props',
     messageCount: 0 },
  properties: 
   { headers: { user_id: '96ce7157f70de72e08b0a8c78300bf1e' },
     userId: 'admin' },
  content: <Buffer 57 61 74 3f> }
```

And the output from RabbitMQ web admin
<img width="543" alt="screen shot 2016-05-26 at 3 48 16 pm" src="https://cloud.githubusercontent.com/assets/617694/15587870/4abcaa8a-2359-11e6-915b-46ddb8c3c7ef.png">

**Comment by jakubkulhan** [comment]
It does indeed, it's a feature.

AMQP spec pre-defines 13 message properties (`content-type`, `content-encoding`, `delivery-mode`, `priority`, `correlation-id`, `reply-to`, `expiration`, `message-id`, `timestamp`, `type`, `user-id`, `app-id`, and `cluster-id`) that are serialized as positional arguments in message header instead of associative array to save bandwidth. `Bunny\Client`'s `publish` extracts these property names from `$headers` parameter, all other (custom) headers are serialized as associative array and sent with request.

---

When you publish message like this:

```
$ch->publish('Hello World!', ['user-id' => 'admin', 'headers' => ['user_id' => '96ce7157f70de72e08b0a8c78300bf1e']], '', 'props');
```

What you actually get is custom header called `headers` with associative array as content:

<img width="541" alt="screenshot 2016-05-31 12 18 13" src="https://cloud.githubusercontent.com/assets/95001/15671187/cd550540-2729-11e6-825b-9b3e0d22618f.png">

RabbitMQ admin's GUI normalizes AMQP messages properties to underscore notation (`user-id` -> `user_id`), Bunny uses dashed notation.

**Comment by cboden** [comment]
Here is a page from [RabbitMQ in Depth](https://www.manning.com/books/rabbitmq-in-depth) discussing the 14 message properties:
![screen shot 2016-05-31 at 9 48 44 am](https://cloud.githubusercontent.com/assets/617694/15676631/ff72bf64-2714-11e6-9904-74c527454162.png)

I do not think the headers key/value pairs should be merged with the message properties.

**Comment by jakubkulhan** [comment]
Maybe if I read RabbitMQ in Depth, I would have implemented the same way as Node AMQP lib 😊 However, this change would break existing implementations of Bunny, so it isn't an option for now.

**Comment by cboden** [comment]
1) This isn't an implementation or langue issue, it's an AMQP protocol issue

2) I understand this will break existing implementation of Bunny, but this is not a feature, it's a bug. 

3) RabbitMQ in Depth teaches about RabbitMQ and the AMQP protocol, not Node...in fact its examples are written in Python. 

Here's another screenshot showing Bunny altering the contents of a message, differentiating from the web admin:
<img width="811" alt="screen shot 2016-06-01 at 9 21 41 am" src="https://cloud.githubusercontent.com/assets/617694/15711047/67fc7afa-27da-11e6-8abb-7870a893de36.png">

**Comment by f3l1x** [comment]
@jakubkulhan Hi Jakub. What is the propel way to have a `headers` exchange with arguments `type: xml` & `type: json`.

```php
$channel->queueBind(
	'name', # queue name
	'exchange', # exchange name
	'', # routing key
	false, # noWait
	['type' => 'json'] # arguments
);

$channel->publish(
	'Test message' # message
	['type' => 'json'], # headers
	'exchange', # exchange name
	'', # routing key
	FALSE, # mandatory
	FALSE # immediate
);
```

Unfortunately this snippet does not work. Thank you for your help.

**Comment by jakubkulhan** [comment]
@f3l1x It is not possible as `type` is extracted from message headers to message properties (https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/ClientMethods.php#L1849-L1855). Frankly, I haven't found any use case for headers exchange, therefore it is implemented as such.

I suggest you use different header name, e.g. `message-type`. Also if you route messages only by single header, this seems to me more like a job for [topic exchange](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-topic).

**Comment by cboden** [comment]
Why was this issue closed? Has the problem been fixed?

**Comment by jakubkulhan** [comment]
@cboden It's a feature.

**Comment by cboden** [comment]
I have provided unequivocal proof this is a bug, not a feature. Bunny is not following the specification; data is being lost. 

I understand the fix is a backwards compatibility break, but please please please fix this issue in a semantic major release.
