### ISSUE TITLE
Tutorial plagiarism

### ISSUE THREAD

**Issue by michaelklishin** [jakubkulhan/bunny#3]
Your README has [the tutorials from rabbitmq.com](http://www.rabbitmq.com/getstarted.html) with slight edits. The footer on the site says

```
Copyright © 2015 Pivotal Software, Inc. All rights reserved
```

Would you mind writing your own tutorials? You haven't even asked the team if it's OK to use their work for your project.

**Comment by michaelklishin** [comment]
I should mention that Bunny (the existing 6 year old Ruby client) [documentation](http://rubybunny.info) is [open source](https://github.com/ruby-amqp/rubybunny.info) and appropriately licensed for you to base your work on it.

**Comment by jakubkulhan** [comment]
I've withdrawn images, code samples and tutorial text. I'll contact Pivotal for permission. Thank you for linking your tutorial, great inspiration!
