### ISSUE TITLE
How consumer can publish message to another queue?

### ISSUE THREAD

**Issue by vxdiv** [jakubkulhan/bunny#33]
When Consumer publish message to another queue - get Exception:

`Exception 'Bunny\Exception\ChannelException' with message 'Unhandled method frame Bunny\Protocol\MethodChannelCloseFrame.'
in /var/www/payments/vendor/bunny/bunny/src/Bunny/Channel.php:613
`

**Comment by ondrejmirtes** [comment]
Client can publish messages to any queue (any exchange to be more precise). Show us the minimal code to reproduce your issue, there's certainly a problem there.

**Comment by vxdiv** [comment]
Sorry, its my mistake.  I send doubled $chanel->ask($msg).
