### ISSUE TITLE
What is Async\Client?

### ISSUE THREAD

**Issue by simPod** [jakubkulhan/bunny#45]
Hi, I'd like to ask what is `Async\Client` in README.md `(new Async\Client($connection)->connect()->then(function (Client $client) {`

Thanks!

**Comment by ondrejmirtes** [comment]
This class? :) https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/Async/Client.php

**Comment by simPod** [comment]
Ok, I feel dumb now. IDE didn't show it to me at first :/ Thanks!
