### ISSUE TITLE
`$channel->queueDeclare($queueName);` never resolves

### ISSUE THREAD

**Issue by Ocramius** [jakubkulhan/bunny#6]
This may be a bug or simply misuse by me (or misunderstanding).

I've taken the example code in [`consumer_async.php`](https://github.com/jakubkulhan/bunny/blob/9317c594852e8a405e249c477847464a51ce071b/benchmark/consumer_async.php#L11-L22) and built following script:

```php

$clientConfig  = [
    \React\EventLoop\Factory::create(),
    ['host' => 'localhost', 'user' => 'guest', 'password' => 'guest'],
];

(new BunnyClient(...$clientConfig))
    ->connect() // works
    ->then(function (BunnyClient $client) {
        return $client->channel(); // works
    })
    ->then(function (Channel $channel) {
        return \React\Promise\all([
            $channel,
            $channel->queueDeclare('queuename') // hangs
        ]);
    })
    ->then(function (array $channels) use ($app) {
        // never reached
        $channels[0]->consume(function (Message $msg) use ($app) {
            echo 'Message received!' . PHP_EOL;
        }, 'queuename');
    });
```

The call `$channel->queueDeclare('queuename')` hangs, and the returned promise is never fulfilled nor rejected.

A few notes on (in my opinion) expected behavior:

 - removing the `queueDeclare` code makes the code work, but only if the channel was already declared by another process
 - if the channel doesn't exist, the app silently hangs without receiving any messages at all

**Comment by Ocramius** [comment]
From further inspection, it seems like it (may be) working if I declare `$channel->queueDeclare('messages', false, false, false, true)`, so if there is a mismatch in the queue definition it just silently crashes.

Still not sure if this is *the* bug though.

**Comment by Ocramius** [comment]
Woah, that was quick!

**Comment by jakubkulhan** [comment]
@Ocramius Thank you for the report! Silly mistake in handling async callbacks :(

**Comment by Ocramius** [comment]
@jakubkulhan I was looking at it without a clue anyway. Will try it ASAP

**Comment by Ocramius** [comment]
This seems to work reliably now, thanks!

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
