### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sm2017** [jakubkulhan/bunny#60]
What is the difference of `MethodQueueDeclareOkFrame` and `MethodQueueDeclareFrame`

**Comment by sm2017** [comment]
@jakubkulhan Please reply me

**Comment by jakubkulhan** [comment]
`MethodQueueDeclareFrame` is sent by client (= request frame), `MethodQueueDeclareOkFrame` is sent back from server (= response frame). See http://www.rabbitmq.com/amqp-0-9-1-quickref.html#queue.declare
