### ISSUE TITLE
Calling `Channel:txSelect` twice throws an error

### ISSUE THREAD

**Issue by yuloh** [jakubkulhan/bunny#67]
If you call `Channel:txSelect` more than once it throws an error, because [the channel is not in regular mode](https://github.com/jakubkulhan/bunny/blob/6421681149f5b531d928f6843eec404f7d5d2f2c/src/Bunny/Channel.php#L463).

The problem is, there is no way to check what mode the channel is in (the property is protected), so I can't actually check if I need to call `txSelect` again.

It seems like there should be a `Channel::getMode` method so you can do:

```php
if ($channel->getMode() !== ChannelModeEnum::TRANSACTIONAL) {
   $channel->txSelect();
}
```

Alternatively `txSelect` could be idempotent but I don't think that will work because the method returns a `MethodTxSelectOkFrame`.

**Comment by jakubkulhan** [comment]
@yuloh Would you send PR with getter for `Channel::$mode`?

**Comment by yuloh** [comment]
> @yuloh What is you use case? (Why do you need to repeatedly set channel to transactional mode?) 

I am not trying to repeatedly call `txSelect`.  I want to only call it once and only if the mode needs to be set, but since there is no way of knowing what mode the channel is in I can't do that.  I am basically trying to do this:

```
if ($channel->getMode() != ChannelModeEnum::TRANSACTIONAL) {
   $channel->txSelect();
}
```

As a workaround I can call `txSelect` as soon as I create the channel and ensure that the channel is only ever used by code that expects a transactional channel, but ideally I would be able to safely use the same channel with and without transactions.

> Would you send PR with getter for Channel::$mode?

Yep, I will send one in a minute.  Thanks!
