### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by boccelio** [jakubkulhan/bunny#71]
Hi,
we have running RabbitMQ on shared domain but on unique port. (vyv.domain.cz:15672)
Bunny could'n reach Rabbit there, but if we put Rabbit on unique domain (rabbit.vyv.domain.cz) there is no problem with connection. 
Is it possible, that bunny have problem with connection on shared domain?
Thans

**Comment by jakubkulhan** [comment]
Hi, this hardly seems to be an issue with the library. 

1. Please check your firewall configuration whether used port number is reachable from the client (you can try that with some [AMQP CLI tool](https://www.google.cz/search?q=amqp+cli)). 
2. Try if DNS resolutions works (`php -r 'var_dump(gethostbyname("vyv.domain.cz"));'`/`dig vyv.domain.cz`).
3. Also if you enable [management plugin](https://www.rabbitmq.com/management.html), by default it uses port 15672 - it might clash with AMQP port.
