### ISSUE TITLE
Connect using SSL protocol

### ISSUE THREAD

**Issue by xorock** [jakubkulhan/bunny#77]
Hello. Is it possible to connect to RabbitMQ using SSL connection? I'm getting error message "RabbitMQ: Broken pipe or closed connection.".

**Comment by jakubkulhan** [comment]
Unfortunately, SSL/TLS connections are not supported.

**Comment by makasim** [comment]
@mywemail you could contribute a feature yourself or paid someone who could do it for you.

**Comment by WyriHaximus** [comment]
FYI: #88
