### ISSUE TITLE
[question] broken pipe or closed connection with large messages

### ISSUE THREAD

**Issue by weemen** [jakubkulhan/bunny#8]
Heey Jakub,

I really like your bunny client but when trying to send large json files I always get an exception: "broken pipe or closed connection"

This always happens at: https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/AbstractClient.php
At the write method.
(sorry I cant see linenumbers on my iPhone).

Do you know if this is a known issue or do you have an idea what might trigger this exception?

Already thanks in advance!

Kind regards Leon

**Comment by rickerd** [comment]
Linenumber 279 is the write method.

**Comment by jakubkulhan** [comment]
@weemen Sorry, I haven't noticed this issue before. Body exceeding one frame wasn't properly handled, fixed now. Thank you for the report.

**Comment by weemen** [comment]
no problem you're welcome :) :+1:
