### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by fhuitelec** [jakubkulhan/bunny#94]
Hi,

Could you release a new version so we can benefit from the work done in https://github.com/jakubkulhan/bunny/pull/88 (SSL support) the with an official release?

Thank you!

**Comment by WyriHaximus** [comment]
@fhuitelec it's on my list for today :+1:

**Comment by WyriHaximus** [comment]
Just tagged [`v0.4.2`](https://github.com/jakubkulhan/bunny/releases/tag/v0.4.2)

**Comment by fhuitelec** [comment]
Great, thank you for your responsiveness!

**Comment by WyriHaximus** [comment]
No problem, been intending to release for a bit now but I keep forgetting. Thank you for the reminder
